"""Initial database schema

Revision ID: 273de7a40217
Revises: 
Create Date: 2025-07-09 11:55:31.677327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273de7a40217'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artworks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('artist', sa.String(length=200), nullable=False),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('depth', sa.Float(), nullable=True),
    sa.Column('medium', sa.String(length=200), nullable=True),
    sa.Column('materials', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provenance', sa.Text(), nullable=True),
    sa.Column('catalog_number', sa.String(length=100), nullable=True),
    sa.Column('accession_number', sa.String(length=100), nullable=True),
    sa.Column('style', sa.String(length=100), nullable=True),
    sa.Column('period', sa.String(length=100), nullable=True),
    sa.Column('subject_matter', sa.Text(), nullable=True),
    sa.Column('reference_image_path', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('visual_features', sa.JSON(), nullable=True),
    sa.Column('color_palette', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog_number')
    )
    op.create_table('exhibitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('museum', sa.String(length=200), nullable=False),
    sa.Column('gallery', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('curator', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('catalog_published', sa.Boolean(), nullable=True),
    sa.Column('catalog_isbn', sa.String(length=20), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('installation_photos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('exhibition_id', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=200), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=True),
    sa.Column('camera_make', sa.String(length=50), nullable=True),
    sa.Column('camera_model', sa.String(length=100), nullable=True),
    sa.Column('capture_date', sa.DateTime(), nullable=True),
    sa.Column('photographer', sa.String(length=200), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('processing_date', sa.DateTime(), nullable=True),
    sa.Column('detection_results', sa.JSON(), nullable=True),
    sa.Column('room', sa.String(length=100), nullable=True),
    sa.Column('wall', sa.String(length=50), nullable=True),
    sa.Column('view_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exhibition_id'], ['exhibitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artwork_appearances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('artwork_id', sa.String(), nullable=False),
    sa.Column('photo_id', sa.String(), nullable=False),
    sa.Column('bbox_x', sa.Float(), nullable=False),
    sa.Column('bbox_y', sa.Float(), nullable=False),
    sa.Column('bbox_width', sa.Float(), nullable=False),
    sa.Column('bbox_height', sa.Float(), nullable=False),
    sa.Column('detection_confidence', sa.Float(), nullable=False),
    sa.Column('matching_confidence', sa.Float(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.String(length=100), nullable=True),
    sa.Column('verification_date', sa.DateTime(), nullable=True),
    sa.Column('cropped_image_path', sa.String(length=500), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('visible_percentage', sa.Float(), nullable=True),
    sa.Column('occlusion_level', sa.String(length=20), nullable=True),
    sa.Column('lighting_quality', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['installation_photos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artwork_appearances')
    op.drop_table('installation_photos')
    op.drop_table('exhibitions')
    op.drop_table('artworks')
    # ### end Alembic commands ###
